const fs = require('fs');

try {
  // Read CTRF Report
  const ctrfRaw = fs.readFileSync('ctrf/ctrf-report.json', 'utf8');
  const ctrfData = JSON.parse(ctrfRaw);
  const summary = ctrfData.results.summary;
  const flakyCount = ctrfData.results.tests.filter(t => t.flaky).length;
  const durationSecs = ((summary.stop - summary.start) / 1000).toFixed(2);

  const repoName = process.env.GITHUB_REPOSITORY || 'aquarian-patil/playwright-typescript-demo';
  const username = repoName.split('/')[0];
  const repo = repoName.split('/')[1];
  const pagesUrl = `https://${username}.github.io/${repo}/`;

  // Generate HTML Email
  const htmlBody = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #ddd; border-radius: 8px;">
      <h2 style="color: #2e6c80; text-align: center;">Playwright Test Automation Run</h2>
      <p style="font-size: 16px; color: #333;">The automated E2E test suite has completed its execution.</p>
      
      <div style="background-color: #f8f9fa; padding: 15px; border-radius: 5px; margin: 20px 0;">
        <h3 style="margin-top: 0; color: #333;">Execution Summary</h3>
        <table style="width: 100%; border-collapse: collapse;">
          <tr style="border-bottom: 1px solid #ddd;">
            <td style="padding: 8px 0; font-weight: bold;">Total Tests:</td>
            <td style="padding: 8px 0; text-align: right;">${summary.tests}</td>
          </tr>
          <tr style="border-bottom: 1px solid #ddd;">
            <td style="padding: 8px 0; font-weight: bold; color: #28a745;">Passed:</td>
            <td style="padding: 8px 0; text-align: right; color: #28a745; font-weight: bold;">${summary.passed}</td>
          </tr>
          <tr style="border-bottom: 1px solid #ddd;">
            <td style="padding: 8px 0; font-weight: bold; color: #dc3545;">Failed:</td>
            <td style="padding: 8px 0; text-align: right; color: #dc3545; font-weight: bold;">${summary.failed}</td>
          </tr>
          <tr style="border-bottom: 1px solid #ddd;">
            <td style="padding: 8px 0; font-weight: bold; color: #6c757d;">Skipped:</td>
            <td style="padding: 8px 0; text-align: right; color: #6c757d; font-weight: bold;">${summary.skipped}</td>
          </tr>
          <tr style="border-bottom: 1px solid #ddd;">
            <td style="padding: 8px 0; font-weight: bold; color: #fd7e14;">Flaky:</td>
            <td style="padding: 8px 0; text-align: right; color: #fd7e14; font-weight: bold;">${flakyCount}</td>
          </tr>
          <tr>
            <td style="padding: 8px 0; font-weight: bold;">Duration:</td>
            <td style="padding: 8px 0; text-align: right;">${durationSecs}s</td>
          </tr>
        </table>
      </div>
      
      <div style="text-align: center; margin: 30px 0;">
        <a href="${pagesUrl}" style="background-color: #007bff; color: white; padding: 12px 24px; text-decoration: none; border-radius: 4px; font-weight: bold; font-size: 16px;">View Full Interactive HTML Report</a>
      </div>
      
      <p style="font-size: 12px; color: #777; text-align: center; margin-top: 30px;">
        This email was automatically generated by GitHub Actions.
      </p>
    </div>
  `;

  // Write HTML to file for the email action to consume
  fs.writeFileSync('email-body.html', htmlBody);
  console.log('Successfully generated email-body.html');
  
} catch (error) {
  console.error('Error generating email body:', error);
  process.exit(1);
}
